name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4

      - if: runner.os == 'macOS'
        run: |
          brew update && brew install gcc

      - if: runner.os == 'macOS'
        run: |
          brew info gcc

      - run: asdf plugin add gambit $GITHUB_WORKSPACE
      - run: asdf install gambit latest
      - run: asdf set gambit latest
      - run: which gsc >/dev/null 2>&1 && gsc -h | grep -q 'This is the Gambit Scheme compiler.'
