name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4

      - if: runner.os == 'macOS'
        run: |
          brew update && brew install gcc
          brew info gcc | grep 'gcc: stable 15'

          echo "CC=$(brew --prefix)/bin/gcc-15" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix)/bin/g++-15" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix)/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV

      - run: asdf plugin add gambit $GITHUB_WORKSPACE
      - run: asdf install gambit latest
      - run: asdf set gambit latest
      - run: which gsc >/dev/null 2>&1 && gsc -h | grep -q 'This is the Gambit Scheme compiler.'
