name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # v4.0.0. https://github.com/asdf-vm/actions/tree/v4.0.0
      - uses: asdf-vm/actions/setup@1902764435ca0dd2f3388eea723a4f92a4eb8302

      - run: asdf plugin add gambit $GITHUB_WORKSPACE
      - run: asdf install gambit latest
      - run: asdf set gambit latest
      - run: which gsc >/dev/null 2>&1 && gsc -h | grep -q 'This is the Gambit Scheme compiler.'
